package com.github.animeshz.globalhooks.keyboard.entity

import com.github.animeshz.globalhooks.keyboard.ExperimentalKeyIO

@Suppress("unused")
@ExperimentalKeyIO
public enum class Key(public val keyCode: Int) {
    Unknown(0),
    Break(0x03),
    Backspace(0x08),
    Tab(0x09),
    Enter(0x0D),
    ShiftLeft(0xA0),
    ShiftRight(0xA1),

    //    SoftLeft(-1),
    //    SoftRight(-1),
    //    Home(KeyEvent.VK_HOME),
    //    Back(-1),
    //    Help(KeyEvent.VK_HELP),
    //    NavigatePrevious(-1),
    //    NavigateNext(-1),
    //    NavigateIn(-1),
    //    NavigateOut(-1),
    //    SystemNavigationUp(-1),
    //    SystemNavigationDown(-1),
    //    SystemNavigationLeft(-1),
    //    SystemNavigationRight(-1),
    //    Call(-1),
    //    EndCall(-1),
    //    DPadUp(KeyEvent.VK_KP_UP),
    //    DPadDown(KeyEvent.VK_KP_DOWN),
    //    DPadLeft(KeyEvent.VK_KP_LEFT),
    //    DPadRight(KeyEvent.VK_KP_RIGHT),
    //    DPadCenter(-1),
    //    DPadUpLeft(-1),
    //    DPadDownLeft(-1),
    //    DPadUpRight(-1),
    //    DPadDownRight(-1),
    //    VolumeUp(-1),
    //    VolumeDown(-1),
    //    Power(-1),
    //    Camera(-1),
    //    Clear(-1),
    //    Number0(KeyEvent.VK_0),
    //    Number1(KeyEvent.VK_1),
    //    Number2(KeyEvent.VK_2),
    //    Number3(KeyEvent.VK_3),
    //    Number4(KeyEvent.VK_4),
    //    Number5(KeyEvent.VK_5),
    //    Number6(KeyEvent.VK_6),
    //    Number7(KeyEvent.VK_7),
    //    Number8(KeyEvent.VK_8),
    //    Number9(KeyEvent.VK_9),
    //    Number11(-1),
    //    Number12(-1),
    //    Plus(KeyEvent.VK_PLUS),
    //    Minus(KeyEvent.VK_MINUS),
    //    Multiply(KeyEvent.VK_MULTIPLY),
    //    Equals(KeyEvent.VK_EQUALS),
    //    Pound(-1),
    //    A(KeyEvent.VK_A),
    //    B(KeyEvent.VK_B),
    //    C(KeyEvent.VK_C),
    //    D(KeyEvent.VK_D),
    //    E(KeyEvent.VK_E),
    //    F(KeyEvent.VK_F),
    //    G(KeyEvent.VK_G),
    //    H(KeyEvent.VK_H),
    //    I(KeyEvent.VK_I),
    //    J(KeyEvent.VK_J),
    //    K(KeyEvent.VK_K),
    //    L(KeyEvent.VK_L),
    //    M(KeyEvent.VK_M),
    //    N(KeyEvent.VK_N),
    //    O(KeyEvent.VK_O),
    //    P(KeyEvent.VK_P),
    //    Q(KeyEvent.VK_Q),
    //    R(KeyEvent.VK_R),
    //    S(KeyEvent.VK_S),
    //    T(KeyEvent.VK_T),
    //    U(KeyEvent.VK_U),
    //    V(KeyEvent.VK_V),
    //    W(KeyEvent.VK_W),
    //    X(KeyEvent.VK_X),
    //    Y(KeyEvent.VK_Y),
    //    Z(KeyEvent.VK_Z),
    //    Comma(KeyEvent.VK_COMMA),
    //    Period(KeyEvent.VK_PERIOD),
    //    AltLeft(KeyEvent.VK_ALT),
    //    AltRight(KeyEvent.VK_ALT),
    //    Spacebar(KeyEvent.VK_SPACE),
    //    Symbol(-1),
    //    Browser(-1),
    //    Envelope(-1),
    //    Delete(KeyEvent.VK_DELETE),
    //    Escape(KeyEvent.VK_ESCAPE),
    //    CtrlLeft(KeyEvent.VK_CONTROL),
    //    CtrlRight(KeyEvent.VK_CONTROL),
    //    CapsLock(KeyEvent.VK_CAPS_LOCK),
    //    ScrollLock(KeyEvent.VK_SCROLL_LOCK),
    //    MetaLeft(KeyEvent.VK_META),
    //    MetaRight(KeyEvent.VK_META),
    //    Function(-1),
    //    PrintScreen(KeyEvent.VK_PRINTSCREEN),
    //
    //    MoveHome(-1),
    //    MoveEnd(-1),
    //    Insert(-1),
    //    Cut(-1),
    //    Copy(-1),
    //    Paste(-1),
    //    Grave(KeyEvent.VK_BACK_QUOTE),
    //    LeftBracket(KeyEvent.VK_OPEN_BRACKET),
    //    RightBracket(KeyEvent.VK_CLOSE_BRACKET),
    //    Slash(KeyEvent.VK_SLASH),
    //    Backslash(KeyEvent.VK_BACK_SLASH),
    //    Semicolon(KeyEvent.VK_SEMICOLON),
    //    Apostrophe(KeyEvent.VK_QUOTE),
    //    At(KeyEvent.VK_AT),
    //    Number(-1),
    //    HeadsetHook(-1),
    //    Focus(-1),
    //    Menu(-1),
    //    Notification(-1),
    //    Search(-1),
    //    PageUp(KeyEvent.VK_PAGE_UP),
    //    PageDown(KeyEvent.VK_PAGE_UP),
    //    PictureSymbols(-1),
    //    SwitchCharset(-1),
    //    ButtonA(-1),
    //    ButtonB(-1),
    //    ButtonC(-1),
    //    ButtonX(-1),
    //    ButtonY(-1),
    //    ButtonZ(-1),
    //    ButtonL1(-1),
    //    ButtonR1(-1),
    //    ButtonL2(-1),
    //    ButtonR2(-1),
    //    ButtonThumbLeft(-1),
    //    ButtonThumbRight(-1),
    //    ButtonStart(-1),
    //    ButtonSelect(-1),
    //    ButtonMode(-1),
    //    Button1(-1),
    //    Button2(-1),
    //    Button3(-1),
    //    Button4(-1),
    //    Button5(-1),
    //    Button6(-1),
    //    Button7(-1),
    //    Button8(-1),
    //    Button9(-1),
    //    Button10(-1),
    //    Button11(-1),
    //    Button12(-1),
    //    Button13(-1),
    //    Button14(-1),
    //    Button15(-1),
    //    Button16(-1),
    //    Forward(-1),
    //    F1(KeyEvent.VK_F1),
    //    F2(KeyEvent.VK_F2),
    //    F3(KeyEvent.VK_F3),
    //    F4(KeyEvent.VK_F4),
    //    F5(KeyEvent.VK_F5),
    //    F6(KeyEvent.VK_F6),
    //    F7(KeyEvent.VK_F7),
    //    F8(KeyEvent.VK_F8),
    //    F9(KeyEvent.VK_F9),
    //    F10(KeyEvent.VK_F10),
    //    F11(KeyEvent.VK_F11),
    //    F12(KeyEvent.VK_F12),
    //    NumLock(KeyEvent.VK_NUM_LOCK),
    //    NumPad0(KeyEvent.VK_NUMPAD0),
    //    NumPad1(KeyEvent.VK_NUMPAD1),
    //    NumPad2(KeyEvent.VK_NUMPAD2),
    //    NumPad3(KeyEvent.VK_NUMPAD3),
    //    NumPad4(KeyEvent.VK_NUMPAD4),
    //    NumPad5(KeyEvent.VK_NUMPAD5),
    //    NumPad6(KeyEvent.VK_NUMPAD6),
    //    NumPad7(KeyEvent.VK_NUMPAD7),
    //    NumPad8(KeyEvent.VK_NUMPAD8),
    //    NumPad9(KeyEvent.VK_NUMPAD9),
    //    NumPadDivide(KeyEvent.VK_DIVIDE),
    //    NumPadMultiply(KeyEvent.VK_MULTIPLY),
    //    NumPadSubtract(KeyEvent.VK_SUBTRACT),
    //    NumPadAdd(KeyEvent.VK_ADD),
    //    NumPadDot(KeyEvent.VK_PERIOD),
    //    NumPadComma(KeyEvent.VK_COMMA),
    //    NumPadEnter(KeyEvent.VK_ENTER),
    //    NumPadEquals(KeyEvent.VK_EQUALS),
    //    NumPadLeftParenthesis(KeyEvent.VK_LEFT_PARENTHESIS),
    //    NumPadRightParenthesis(KeyEvent.VK_RIGHT_PARENTHESIS),
    //    MediaPlay(-1),
    //    MediaPause(-1),
    //    MediaPlayPause(-1),
    //    MediaStop(-1),
    //    MediaRecord(-1),
    //    MediaNext(-1),
    //    MediaPrevious(-1),
    //    MediaRewind(-1),
    //    MediaFastForward(-1),
    //    MediaClose(-1),
    //    MediaAudioTrack(-1),
    //    MediaEject(-1),
    //    MediaTopMenu(-1),
    //    MediaSkipForward(-1),
    //    MediaSkipBackward(-1),
    //    MediaStepForward(-1),
    //    MediaStepBackward(-1),
    //    MicrophoneMute(-1),
    //    VolumeMute(-1),
    //    Info(-1),
    //    ChannelUp(-1),
    //    ChannelDown(-1),
    //    ZoomIn(-1),
    //    ZoomOut(-1),
    //    Tv(-1),
    //    Window(-1),
    //    Guide(-1),
    //    Dvr(-1),
    //    Bookmark(-1),
    //    Captions(-1),
    //    Settings(-1),
    //    TvPower(-1),
    //    TvInput(-1),
    //    SetTopBoxPower(-1),
    //    SetTopBoxInput(-1),
    //    AvReceiverPower(-1),
    //    AvReceiverInput(-1),
    //    ProgramRed(-1),
    //    ProgramGreen(-1),
    //    ProgramYellow(-1),
    //    ProgramBlue(-1),
    //    AppSwitch(-1),
    //    LanguageSwitch(-1),
    //    MannerMode(-1),
    //    Toggle2D3D(-1),
    //    Contacts(-1),
    //    Calendar(-1),
    //    Music(-1),
    //    Calculator(-1),
    //    ZenkakuHankaru(-1),
    //    Eisu(-1),
    //    Muhenkan(-1),
    //    Henkan(-1),
    //    KatakanaHiragana(-1),
    //    Yen(-1),
    //    Ro(-1),
    //    Kana(-1),
    //    Assist(-1),
    //    BrightnessDown(-1),
    //    BrightnessUp(-1),
    //    Sleep(-1),
    //    WakeUp(-1),
    //    SoftSleep(-1),
    //    Pairing(-1),
    //    LastChannel(-1),
    //    TvDataService(-1),
    //    VoiceAssist(-1),
    //    TvRadioService(-1),
    //    TvTeletext(-1),
    //    TvNumberEntry(-1),
    //    TvTerrestrialAnalog(-1),
    //    TvTerrestrialDigital(-1),
    //    TvSatellite(-1),
    //    TvSatelliteBs(-1),
    //    TvSatelliteCs(-1),
    //    TvSatelliteService(-1),
    //    TvNetwork(-1),
    //    TvAntennaCable(-1),
    //    TvInputHdmi1(-1),
    //    TvInputHdmi2(-1),
    //    TvInputHdmi3(-1),
    //    TvInputHdmi4(-1),
    //    TvInputComposite1(-1),
    //    TvInputComposite2(-1),
    //    TvInputComponent1(-1),
    //    TvInputComponent2(-1),
    //    TvInputVga1(-1),
    //    TvAudioDescription(-1),
    //    TvAudioDescriptionMixingVolumeUp(-1),
    //    TvAudioDescriptionMixingVolumeDown(-1),
    //    TvZoomMode(-1),
    //    TvContentsMenu(-1),
    //    TvMediaContextMenu(-1),
    //    TvTimerProgramming(-1),
    //    StemPrimary(-1),
    //    Stem1(-1),
    //    Stem2(-1),
    //    Stem3(-1),
    //    AllApps(-1),
    //    Refresh(-1),
    //    ThumbsUp(-1),
    //    ThumbsDown(-1),
    //    ProfileSwitch(-1),
    ;

    override fun toString(): String {
        return "Key.$name(keyCode=$keyCode)"
    }

    public companion object {
        public fun fromKeyCode(keyCode: Int): Key {
            //            val values = values()

            //            var start = 0
            //            var end = values.size

            //            while (start < end) {
            //                var mid = (start + end) / 2
            //
            //            }

            return Unknown
        }

        private fun binarySearch() {

        }
    }
}
